server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        # This tries to match the URL to a .pdf or .html file automatically
        try_files $uri $uri.pdf $uri.html $uri/ =404;
    }

    # Force download for PDFs
    location ~* \.pdf$ {
        add_header Content-Disposition "attachment";
    }
}
